version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/database:/backend/database
    deploy:
      replicas: 3
      
  frontend:
    build:
      context: ./frontend/community-streak
    ports:
      - "3000:3000"
    depends_on:
      - backend


# docker-compose up --build