name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint --disable=E0401 --disable=C0301 --disable=C0103 --disable=R0903 --disable=W0718 $(git ls-files '*.py') || true
        pylint_score=$(pylint --disable=E0401 --disable=C0301 --disable=C0103 --disable=R0903 --disable=W0718 $(git ls-files '*.py') | grep 'Your code has been rated at' | awk '{print $7}' | cut -d'/' -f1)
        if (( $(echo "$pylint_score < 7" | bc -l) )); then
          echo "Pylint score is below 7: $pylint_score"
          exit 1
        else
          echo "Pylint score is above 7: $pylint_score"
        fi
