name: Run Pytest

on:
    push:
        paths:
            - 'backend/**'
    pull_request:
        paths:
            - 'backend/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
    
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
    
            - name: Install dependencies
              run: |
                cd backend
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Create .env file
              run: |
              cd backend
              echo "secret_key=your_secret_key_value" >> .env
              echo "token_refresh_key=your_refresh_secret_key_value" >> .env
              echo "database_url=sqlite:///./database/community_streak.db" >> .env
              echo "debug_level=10" >> .env

            - name: Run Pytest
              run: |
                cd backend
                pytest -p no:warnings